// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// isotopefit_opt_cpp
Rcpp::NumericVector isotopefit_opt_cpp(const DataFrame& spectrum, const DataFrame& isotope_template, double poi, double ppm_tolerance, double cosine_score_correction, NumericVector minimal_isotope_sequence, std::string score);
RcppExport SEXP _IsoTrac_isotopefit_opt_cpp(SEXP spectrumSEXP, SEXP isotope_templateSEXP, SEXP poiSEXP, SEXP ppm_toleranceSEXP, SEXP cosine_score_correctionSEXP, SEXP minimal_isotope_sequenceSEXP, SEXP scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type spectrum(spectrumSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type isotope_template(isotope_templateSEXP);
    Rcpp::traits::input_parameter< double >::type poi(poiSEXP);
    Rcpp::traits::input_parameter< double >::type ppm_tolerance(ppm_toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type cosine_score_correction(cosine_score_correctionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minimal_isotope_sequence(minimal_isotope_sequenceSEXP);
    Rcpp::traits::input_parameter< std::string >::type score(scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(isotopefit_opt_cpp(spectrum, isotope_template, poi, ppm_tolerance, cosine_score_correction, minimal_isotope_sequence, score));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IsoTrac_isotopefit_opt_cpp", (DL_FUNC) &_IsoTrac_isotopefit_opt_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_IsoTrac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
